version: '2.1'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /home/docker/portainer:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no" # because the exit code(s) are wrong

  organizr:
    container_name: organizr
    image: linuxserver/organizr
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/docker/organizr:/config:rw
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - PGID=1000
      - PUID=1000
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 5

  dockermon:
    container_name: dockermon
    image: philhawthorne/ha-dockermon
    ports:
      - 8126:8126
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/docker/dockermon:/config
    restart: on-failure

  tasmoadmin:
    container_name: tasmoadmin
    image: raymondmm/tasmoadmin
    ports:
      - 9541:80
    volumes:
      - /home/docker/tasmoadmin:/data:rw
    restart: on-failure
